FROM odoo-fourteen-base:0.1.h
MAINTAINER Prologue SOLUTIONS <entreprise@prologue-solutions.tn>

# install prerequisites

# Set default user when running the container
USER odoo

ENTRYPOINT ["/entrypoint.sh"]
CMD ["odoo"]
